version: '3.8'

services:
  thesketch.webapi:
    image: ${DOCKER_REGISTRY-}thesketchwebapi
    container_name: thesketch.webapi
    build:
      context: .
      dockerfile: TheSketch.WebApi/Dockerfile
    ports:
      - "5000:8000"
      - "5001:8001"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgreSQL=Host=thesketch.database;Port=5432;Database=thesketch;Username=thesketch;Password=thesketch
    depends_on:
      - thesketch.database

  thesketch.database:
    image: postgres:latest
    container_name: thesketch.database
    environment:
      POSTGRES_USER: thesketch
      POSTGRES_PASSWORD: thesketch
      POSTGRES_DB: thesketch
    volumes:
      - thesketch-data:/var/lib/postgresql
    ports:
      - "5432:5432"

volumes:
  thesketch-data: